name: HACS

permissions:
  contents: read

on:
  push: 
  pull_request:
  schedule:
    - cron: "0 6 * * 6"

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
