name: HACS

permissions:
  contents: read

on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * 6"

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@dcb30e72781db3f207d5236b861172774ab0b485" # main
        with:
          category: "integration"
          ignore: "brands"
