name: Hassfest

permissions:
  contents: read

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 6 * * 6'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"
